export const stateList=[
    {
        id: crypto.randomUUID(),
        name: "Andhra Pradesh",
        ministries: {
            Chief_Minister: "Y. S. Jagan Mohan Reddy",
            Home_Minister: "M. Sucharita",
            Finance_Minister: "B. Rajendranath Reddy",
            Education_Minister: "Botsa Satyanarayana"
        },
        districts: [
            "Ananthapur",
            "Chittoor",
            "East Godavari",
            "Guntur",
            "Krishna",
            "Kurnool",
            "Nellore",
            "Prakasam",
            "Srikakulam",
            "Visakhapatnam",
            "Vizianagaram",
            "West Godavari",
            "YSR Kadapa"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Arunachal Pradesh",
        ministries: {
            Chief_Minister: "Pema Khandu",
            Home_Minister: "Bamang Felix",
            Finance_Minister: "Karma Tagar",
            Education_Minister: "Taba Tedir"
        },
        districts: [
            "Aalo",
            "Anjaw",
            "Changlang",
            "Dibang Valley",
            "East Kameng",
            "East Siang",
            "Itanagar",
            "Kra Daadi",
            "Lepa Rada",
            "Lower Dibang Valley",
            "Lower Subansiri",
            "Namsai",
            "Papum Pare",
            "Tawang",
            "Tirap",
            "Upper Dibang Valley",
            "Upper Siang",
            "West Kameng",
            "West Siang"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Assam",
        ministries: {
            Chief_Minister: "Himanta Biswa Sarma",
            Home_Minister: "Gaurav Gogoi",
            Finance_Minister: "Ajanta Neog",
            Education_Minister: "Ranoj Pegu"
        },
        districts: [
            "Baksa",
            "Barpeta",
            "Bishnupur",
            "Darrang",
            "Dibrugarh",
            "Goalpara",
            "Golaghat",
            "Hailakandi",
            "Jorhat",
            "Kamrup",
            "Karimganj",
            "Kokrajhar",
            "Lakhimpur",
            "Morigaon",
            "Nagaon",
            "Nalbari",
            "Sivasagar",
            "Sonitpur",
            "Tinsukia",
            "Udalguri",
            "West Karbi Anglong"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Bihar",
        ministries: {
            Chief_Minister: "Nitish Kumar",
            Home_Minister: "Rajendra Prasad",
            Finance_Minister: "Vijay Kumar Chaudhary",
            Education_Minister: "Ashok Choudhary"
        },
        districts: [
            "Araria",
            "Arwal",
            "Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bihar Sharif",
            "Buxar",
            "Darbhanga",
            "Gaya",
            "Gopalganj",
            "Jamui",
            "Jehanabad",
            "Kaimur",
            "Katihar",
            "Khagaria",
            "Kishanganj",
            "Lakhisarai",
            "Madhepura",
            "Madhubani",
            "Munger",
            "Nalanda",
            "Nawada",
            "Patna",
            "Purnea",
            "Rohtas",
            "Saran",
            "Sheikhpura",
            "Sitamarhi",
            "Supaul",
            "Vaishali",
            "West Champaran"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Chhattisgarh",
        ministries: {
            Chief_Minister: "Bhupesh Baghel",
            Home_Minister: "Tamradhwaj Sahu",
            Finance_Minister: "T. S. Singh Deo",
            Education_Minister: "Premsai Singh Tekam"
        },
        districts: [
            "Balod",
            "Baloda Bazar",
            "Bemetara",
            "Bilaspur",
            "Dantewada",
            "Dhamtari",
            "Durg",
            "Gariaband",
            "JanJGir-Champa",
            "Jashpur",
            "Kanker",
            "Kondagaon",
            "Korba",
            "Mahasamund",
            "Raigarh",
            "Raipur",
            "Rajnandgaon",
            "Sukma",
            "Surguja"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Goa",
        ministries: {
            Chief_Minister: "Pramod Sawant",
            Home_Minister: "Shri Amit Shah",
            Finance_Minister: "Jaisheela Kharvi",
            Education_Minister: "Vishwajit Rane"
        },
        districts: [
            "North Goa",
            "South Goa"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Gujarat",
        ministries: {
            Chief_Minister: "Bhupendra Patel",
            Home_Minister: "Harsh Sanghavi",
            Finance_Minister: "Kanu Desai",
            Education_Minister: "K. R. K. Ramesh"
        },
        districts: [
            "Ahmedabad",
            "Amreli",
            "Anand",
            "Banaskantha",
            "Bharuch",
            "Bhavnagar",
            "Dahod",
            "Dangs",
            "Gandhinagar",
            "Kutch",
            "Kheda",
            "Mahisagar",
            "Mehsana",
            "Narmada",
            "Navsari",
            "Panchmahal",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Sabarkantha",
            "Surat",
            "Surendranagar",
            "Vadodara",
            "Valsad"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Haryana",
        ministries: {
            Chief_Minister: "Manohar Lal Khattar",
            Home_Minister: "Anil Vij",
            Finance_Minister: "Capt. Abhimanyu",
            Education_Minister: "Kanwar Pal"
        },
        districts: [
            "Ambala",
            "Bhiwani",
            "Charkhi Dadri",
            "Faridabad",
            "Fatehabad",
            "Gurugram",
            "Hisar",
            "Jhajjar",
            "Jind",
            "Kaithal",
            "Karnal",
            "Mahendragarh",
            "Nuh",
            "Panchkula",
            "Panipat",
            "Rewari",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Yamunanagar"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Himachal Pradesh",
        ministries: {
            Chief_Minister: "Sukhvinder Singh Sukhu",
            Home_Minister: "Rohit Thakur",
            Finance_Minister: "Rohit Thakur",
            Education_Minister: "Rohit Thakur"
        },
        districts: [
            "Bilaspur",
            "Chamba",
            "Hamirpur",
            "Kinnaur",
            "Kullu",
            "Lahaul and Spiti",
            "Mandi",
            "Shimla",
            "Sirmaur",
            "Solan",
            "Una"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Jharkhand",
        ministries: {
            Chief_Minister: "Hemant Soren",
            Home_Minister: "B. W. L. D. W. G. S. P. S.",
            Finance_Minister: "Rameshwar Oraon",
            Education_Minister: "Jagarnath Mahto"
        },
        districts: [
            "Bokaro",
            "Chatra",
            "Dhanbad",
            "Dumka",
            "East Singhbhum",
            "Garhwa",
            "Giridih",
            "Godda",
            "Gumla",
            "Hazaribagh",
            "Jamtara",
            "Khunti",
            "Koderma",
            "Latehar",
            "Lohardaga",
            "Pakur",
            "Palamu",
            "Ranchi",
            "Sahebganj",
            "Seraikela Kharsawan",
            "West Singhbhum"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Karnataka",
        ministries: {
            Chief_Minister: "Siddaramaiah",
            Home_Minister: "G. Parameshwara",
            Finance_Minister: "N. Manjunath",
            Education_Minister: "Madhu Bangarappa"
        },
        districts: [
            "Bagalkot",
            "Ballari",
            "Belagavi",
            "Bengaluru Rural",
            "Bengaluru Urban",
            "Bidar",
            "Chamarajanagar",
            "Chikkaballapur",
            "Chikkamagaluru",
            "Chitradurga",
            "Dakshina Kannada",
            "Davanagere",
            "Dharwad",
            "Gadag",
            "Hassan",
            "Haveri",
            "Kodagu",
            "Kolar",
            "Koppal",
            "Mandya",
            "Mysuru",
            "Raichur",
            "Ramanagara",
            "Shivamogga",
            "Tumakuru",
            "Udupi",
            "Uttara Kannada",
            "Vijayapura",
            "Yadgir"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Kerala",
        ministries: {
            Chief_Minister: "Pinarayi Vijayan",
            Home_Minister: "Mohammed Riyas",
            Finance_Minister: "K. N. Balagopal",
            Education_Minister: "V. Shivankutty"
        },
        districts: [
            "Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kozhikode",
            "Kollam",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thiruvananthapuram",
            "Wayanad",
            "Kottayam",
            "Kannur",
            "Kasargod"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Madhya Pradesh",
        ministries: {
            Chief_Minister: "Shivraj Singh Chouhan",
            Home_Minister: "Narottam Mishra",
            Finance_Minister: "Jitu Patwari",
            Education_Minister: "Inder Singh Parmar"
        },
        districts: [
            "Agar Malwa",
            "Alirajpur",
            "Anuppur",
            "Ashoknagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa",
            "Khargone",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panchmarhi",
            "Panna",
            "Raisen",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Satna",
            "Sehore",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Maharashtra",
        ministries: {
            Chief_Minister: "Eknath Shinde",
            Home_Minister: "Devendra Fadnavis",
            Finance_Minister: "Raja S. K. N. M. R.",
            Education_Minister: "Deepak Kesarkar"
        },
        districts: [
            "Ahmednagar",
            "Akola",
            "Aurangabad",
            "Beed",
            "Bhandara",
            "Buldhana",
            "Chandrapur",
            "Dhule",
            "Gadchiroli",
            "Gondia",
            "Hingoli",
            "Jalna",
            "Jalgaon",
            "Kolhapur",
            "Latur",
            "Mumbai",
            "Nagpur",
            "Nanded",
            "Nashik",
            "Osmanabad",
            "Palghar",
            "Parbhani",
            "Pune",
            "Raigad",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sindhudurg",
            "Solapur",
            "Thane",
            "Wardha",
            "Washim",
            "Yavatmal"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Manipur",
        ministries: {
            Chief_Minister: "N. Biren Singh",
            Home_Minister: "K. B. Shyam",
            Finance_Minister: "K. Govindas",
            Education_Minister: "Sorokhaibam Rajen Singh"
        },
        districts: [
            "Bishnupur",
            "Chandel",
            "Churachandpur",
            "Imphal East",
            "Imphal West",
            "Jiribam",
            "Kakching",
            "Kamjong",
            "Kangpokpi",
            "Noney",
            "Pherzawl",
            "Senapati",
            "Tamenglong",
            "Tengnoupal",
            "Thoubal",
            "Ukhrul"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Meghalaya",
        ministries: {
            Chief_Minister: "Conrad Sangma",
            Home_Minister: "Lahkmen Rymbui",
            Finance_Minister: "Prestone Tynsong",
            Education_Minister: "Rohit Sangma"
        },
        districts: [
            "East Garo Hills",
            "East Khasi Hills",
            "North Garo Hills",
            "Ri Bhoi",
            "South Garo Hills",
            "South Khasi Hills",
            "West Garo Hills",
            "West Khasi Hills"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Mizoram",
        ministries: {
            Chief_Minister: "Zoramthanga",
            Home_Minister: "Laldenga",
            Finance_Minister: "Lalchhandama Ralte",
            Education_Minister: "Zoramthanga"
        },
        districts: [
            "Aizawl",
            "Champhai",
            "Hnahthial",
            "Khawzawl",
            "Kolasib",
            "Lawngtlai",
            "Lunglei",
            "Mamit",
            "Saiha",
            "Serchhip"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Nagaland",
        ministries: {
            Chief_Minister: "Neiphiu Rio",
            Home_Minister: "Y. Patton",
            Finance_Minister: "N. L. Khaplang",
            Education_Minister: "Temjen Imna Along"
        },
        districts: [
            "Dimapur",
            "Kiphire",
            "Longleng",
            "Mokokchung",
            "Mon",
            "Peren",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Odisha",
        ministries: {
            Chief_Minister: "Naveen Patnaik",
            Home_Minister: "B. K. Arukh",
            Finance_Minister: "Niranjan Pujari",
            Education_Minister: "Samir Ranjan Dash"
        },
        districts: [
            "Angul",
            "Balangir",
            "Balasore",
            "Bargarh",
            "Bhadrak",
            "Bolangir",
            "Deogarh",
            "Dhenkanal",
            "Ganjam",
            "Gajapati",
            "Jajpur",
            "Jagatsinghpur",
            "Jharsuguda",
            "Kalahandi",
            "Kandhamal",
            "Keonjhar",
            "Khurda",
            "Koraput",
            "Nabarangpur",
            "Nayagarh",
            "Nuapada",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Sundargarh"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Punjab",
        ministries: {
            Chief_Minister: "Bhagwant Mann",
            Home_Minister: "Sukhjinder Singh Randhawa",
            Finance_Minister: "Harpal Singh Cheema",
            Education_Minister: "Gurmeet Singh Meet Hayer"
        },
        districts: [
            "Amritsar",
            "Barnala",
            "Bathinda",
            "Fatehgarh Sahib",
            "Fazilka",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Pathankot",
            "Rupnagar",
            "Sangrur",
            "Shaheed Bhagat Singh Nagar",
            "Tarn Taran"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Rajasthan",
        ministries: {
            Chief_Minister: "Ashok Gehlot",
            Home_Minister: "Sukhram Vishnoi",
            Finance_Minister: "Tarun Kumawat",
            Education_Minister: "Bhanwar Singh Bhati"
        },
        districts: [
            "Ajmer",
            "Alwar",
            "Banswara",
            "Baran",
            "Barmer",
            "Bhilwara",
            "Bikaner",
            "Chittorgarh",
            "Churu",
            "Dausa",
            "Dholpur",
            "Dungarpur",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jhalawar",
            "Jhunjhunu",
            "Nagaur",
            "Pali",
            "Rajsamand",
            "Sawai Madhopur",
            "Sikar",
            "Tonk",
            "Udaipur"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Sikkim",
        ministries: {
            Chief_Minister: "Prem Singh Tamang",
            Home_Minister: "K. N. Lepcha",
            Finance_Minister: "K. N. Lepcha",
            Education_Minister: "K. N. Lepcha"
        },
        districts: [
            "East Sikkim",
            "North Sikkim",
            "South Sikkim",
            "West Sikkim"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Tamil Nadu",
        ministries: {
            Chief_Minister: "M. K. Stalin",
            Home_Minister: "V. Senthil Balaji",
            Finance_Minister: "Thangam Thennarasu",
            Education_Minister: "Anbil Mahesh Poyyamozhi"
        },
        districts: [
            "Ariyalur",
            "Chengalpattu",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kallakurichi",
            "Kanyakumari",
            "Karur",
            "Krishnagiri",
            "Madurai",
            "Nagapattinam",
            "Namakkal",
            "Nilgiris",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Ranipet",
            "Salem",
            "Sivagangai",
            "Tenkasi",
            "Thanjavur",
            "Theni",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tiruvarur",
            "Vellore",
            "Villupuram",
            "Virudhunagar"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Telangana",
        ministries: {
            Chief_Minister: "K. Chandrashekar Rao",
            Home_Minister: "Mohammed Mahmood Ali",
            Finance_Minister: "T. Harish Rao",
            Education_Minister: "P. Sabitha Indra Reddy"
        },
        districts: [
            "Adilabad",
            "Hyderabad",
            "Jagtiyal",
            "Jagtial",
            "Jangaon",
            "Jayashankar Bhupalpally",
            "Jogulamba Gadwal",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Mahabubnagar",
            "Mancherial",
            "Medak",
            "Medchal-Malkajgiri",
            "Nalgonda",
            "Nizamabad",
            "Peddapalli",
            "Rajanna Sircilla",
            "Rangareddy",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Warangal Rural",
            "Warangal Urban",
            "Yadadri Bhuvanagiri"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Tripura",
        ministries: {
            Chief_Minister: "Manik Saha",
            Home_Minister: "Sushanta Chowdhury",
            Finance_Minister: "Pranajit Singha Roy",
            Education_Minister: "Ratan Lal Nath"
        },
        districts: [
            "Agartala",
            "Dhalai",
            "Gomati",
            "Khowai",
            "North Tripura",
            "Sepahijala",
            "South Tripura",
            "Unakoti",
            "West Tripura"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Uttar Pradesh",
        ministries: {
            Chief_Minister: "Yogi Adityanath",
            Home_Minister: "Braj Mohan Shukla",
            Finance_Minister: "Suresh Kumar Khanna",
            Education_Minister: "Yogi Adityanath"
        },
        districts: [
            "Agra",
            "Aligarh",
            "Allahabad",
            "Ambedkarnagar",
            "Amethi",
            "Auraiya",
            "Azamgarh",
            "Badaun",
            "Bahraich",
            "Balrampur",
            "Banda",
            "Barabanki",
            "Bareilly",
            "Bhadohi",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Chandauli",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Etawah",
            "Faizabad",
            "Farrukhabad",
            "Fatehpur",
            "Firozabad",
            "Gautam Buddh Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Gorakhpur",
            "Hamirpur",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Kannauj",
            "Kanpur",
            "Kaushambi",
            "Kheri",
            "Kushinagar",
            "Lakhimpur Kheri",
            "Lucknow",
            "Maharajganj",
            "Mahoba",
            "Mainpuri",
            "Mathura",
            "Mau",
            "Meerut",
            "Mirzapur",
            "Mohammadabad",
            "Pilibhit",
            "Pratapgarh",
            "Raebareli",
            "Rampur",
            "Saharanpur",
            "Sambhal",
            "Shahjahanpur",
            "Shrawasti",
            "Siddharthnagar",
            "Sonbhadra",
            "Sultanpur",
            "Unnao",
            "Varanasi",
            "Shahjahanpur"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "Uttarakhand",
        ministries: {
            Chief_Minister: "Pushkar Singh Dhami",
            Home_Minister: "Dhan Singh Rawat",
            Finance_Minister: "Prakash Pant",
            Education_Minister: "Arvind Pandey"
        },
        districts: [
            "Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi"
        ]
    },
    {
        id: crypto.randomUUID(),
        name: "West Bengal",
        ministries: {
            Chief_Minister: "Mamata Banerjee",
            Home_Minister: "Narayan Dutta",
            Finance_Minister: "Amit Mitra",
            Education_Minister: "Bratya Basu"
        },
        districts: [
            "Alipurduar",
            "Bankura",
            "Birbhum",
            "Burdwan",
            "Cooch Behar",
            "Dakshin Dinajpur",
            "Darjeeling",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Jhargram",
            "Malda",
            "Medinipur",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "Purba Bardhaman",
            "Purulia",
            "South 24 Parganas",
            "Uttar Dinajpur",
            "Kolkata"
        ]
    }
]
