export const stateList= [
    {
        id: crypto.randomUUID(),
        name: "Andhra Pradesh",
        ministries: {
            chief_minister: "Y. S. Jagan Mohan Reddy",
            home_minister: "Mekathoti Sucharita",
            finance_minister: "Buggana Rajendranath"
        },
        districts: [
            "Anantapur",
            "Chittoor",
            "East Godavari",
            "Guntur",
            "Krishna",
            "Kurnool",
            "Prakasam",
            "Srikakulam",
            "Sri Potti Sriramulu Nellore",
            "Visakhapatnam",
            "Vizianagaram",
            "West Godavari",
            "YSR Kadapa"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Andhra-Pradesh.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Bihar",
        ministries: {
            chief_minister: "Nitish Kumar",
            home_minister: "Nitish Kumar",
            finance_minister: "Vijay Kumar Choudhary"
        },
        districts: [
            "Araria",
            "Arwal",
            "Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "Darbhanga",
            "East Champaran",
            "Gaya",
            "Gopalganj",
            "Jamui",
            "Jehanabad",
            "Kaimur",
            "Katihar",
            "Khagaria",
            "Madhepura",
            "Madhubani",
            "Munger",
            "Nalanda",
            "Nawada",
            "Patna",
            "Purnia",
            "Rohtas",
            "Saharsa",
            "Samastipur",
            "Saran",
            "Sheikhpura",
            "Sheohar",
            "Sitamarhi",
            "Siwan",
            "Supaul",
            "Vaishali",
            "West Champaran"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Bihar.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Chhattisgarh",
        ministries: {
            chief_minister: "Bhupesh Baghel",
            home_minister: "Tamradhwaj Sahu",
            finance_minister: "T. S. Singh Deo"
        },
        districts: [
            "Balod",
            "Baloda Bazar",
            "Dantewada",
            "Dhamtari",
            "Durg",
            "Gariaband",
            "JanJGir-Champa",
            "Korba",
            "Koriya",
            "Mahasamund",
            "Raigarh",
            "Raipur",
            "Rajnandgaon",
            "Surguja"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Chhattisgarh.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Goa",
        ministries: {
            chief_minister: "Pramod Sawant",
            home_minister: "Shripad Naik",
            finance_minister: "Pramod Sawant"
        },
        districts: [
            "North Goa",
            "South Goa"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Goa.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Gujarat",
        ministries: {
            chief_minister: "Bhupendra Patel",
            home_minister: "Harsh Sanghavi",
            finance_minister: "Kanu Desai"
        },
        districts: [
            "Ahmedabad",
            "Amreli",
            "Anand",
            "Aravalli",
            "Banaskantha",
            "Bharuch",
            "Bhavnagar",
            "Dahod",
            "Dangs",
            "Gandhinagar",
            "Gir Somnath",
            "Jamnagar",
            "Junagadh",
            "Kutch",
            "Kheda",
            "Mahisagar",
            "Mehsana",
            "Narmada",
            "Navsari",
            "Panchmahal",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Sabarkantha",
            "Surat",
            "Surendranagar",
            "Vadodara",
            "Valsad"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Gujarat.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Haryana",
        ministries: {
            chief_minister: "Manohar Lal Khattar",
            home_minister: "Anil Vij",
            finance_minister: "Capt. Abhimanyu"
        },
        districts: [
            "Ambala",
            "Bhiwani",
            "Charkhi Dadri",
            "Faridabad",
            "Fatehabad",
            "Gurugram",
            "Hisar",
            "Jhajjar",
            "Jind",
            "Kaithal",
            "Karnal",
            "Mahendragarh",
            "Panchkula",
            "Panipat",
            "Rewari",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Yamunanagar"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Haryana.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Himachal Pradesh",
        ministries: {
            chief_minister: "Jai Ram Thakur",
            home_minister: "Rohit Thakur",
            finance_minister: "Ram Lal Markanda"
        },
        districts: [
            "Bilaspur",
            "Chamba",
            "Hamirpur",
            "Kinnaur",
            "Kullu",
            "Lahaul and Spiti",
            "Mandi",
            "Shimla",
            "Sirmaur",
            "Solan",
            "Una"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Himachal-Pradesh.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Jharkhand",
        ministries: {
            chief_minister: "Hemant Soren",
            home_minister: "Ramchandra Chandravanshi",
            finance_minister: "Rameshwar Oraon"
        },
        districts: [
            "Bokaro",
            "Chatra",
            "Dhanbad",
            "Dumka",
            "East Singhbhum",
            "Garhwa",
            "Giridih",
            "Godda",
            "Gumla",
            "Hazaribagh",
            "Jamtara",
            "Khunti",
            "Koderma",
            "Latehar",
            "Lohardaga",
            "Pakur",
            "Palamu",
            "Ranchi",
            "Sahibganj",
            "Seraikela Kharsawan",
            "Simdega",
            "West Singhbhum"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Jharkhand.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Karnataka",
        ministries: {
            chief_minister: "Basavaraj Bommai",
            home_minister: "Araga Jnanendra",
            finance_minister: "Nirmal Kumar Surana"
        },
        districts: [
            "Bagalkote",
            "Ballari",
            "Bangalore Rural",
            "Bangalore Urban",
            "Belagavi",
            "Bellary",
            "Bengaluru",
            "Bidar",
            "Chamarajanagar",
            "Chikballapur",
            "Chikkamagaluru",
            "Chitradurga",
            "Dakshina Kannada",
            "Davanagere",
            "Dharwad",
            "Gadag",
            "Hassan",
            "Haveri",
            "Kodagu",
            "Kolar",
            "Koppal",
            "Mandya",
            "Mysuru",
            "Raichur",
            "Ramanagara",
            "Shivamogga",
            "Tumakuru",
            "Udupi",
            "Uttara Kannada",
            "Vijayapura",
            "Yadgir"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Karnataka.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Kerala",
        ministries: {
            chief_minister: "Pinarayi Vijayan",
            home_minister: "Mohammed Riyas",
            finance_minister: "K. N. Balagopal"
        },
        districts: [
            "Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thiruvananthapuram",
            "Thrissur",
            "Wayanad"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Kerala.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Madhya Pradesh",
        ministries: {
            chief_minister: "Shivraj Singh Chouhan",
            home_minister: "Narottam Mishra",
            finance_minister: "Jagdish Deora"
        },
        districts: [
            "Agar Malwa",
            "Alirajpur",
            "Anuppur",
            "Ashoknagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dindori",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panna",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Satna",
            "Sehore",
            "Senapati",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Madhya-Pradesh.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Maharashtra",
        ministries: {
            chief_minister: "Eknath Shinde",
            home_minister: "Devendra Fadnavis",
            finance_minister: "Devendra Fadnavis"
        },
        districts: [
            "Ahmednagar",
            "Akola",
            "Aurangabad",
            "Bhandara",
            "Buldhana",
            "Chandrapur",
            "Dhule",
            "Gadchiroli",
            "jalna",
            "Jalna",
            "Kolhapur",
            "Latur",
            "Mumbai",
            "Nagpur",
            "Nanded",
            "Nandurbar",
            "Nasik",
            "Osmanabad",
            "Parbhani",
            "Pune",
            "Raigad",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sindhudurg",
            "Solapur",
            "Thane",
            "Wardha",
            "Washim",
            "Yavatmal"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Maharashtra.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Manipur",
        ministries: {
            chief_minister: "N. Biren Singh",
            home_minister: "N. Biren Singh",
            finance_minister: "Th. Biswajit Singh"
        },
        districts: [
            "Bishnupur",
            "Chandel",
            "Churachandpur",
            "Imphal East",
            "Imphal West",
            "Jiribam",
            "Kakching",
            "Kamjong",
            "Kangpokpi",
            "Noney",
            "Pherzawl",
            "Senapati",
            "Tamenglong",
            "Tengnoupal",
            "Thoubal",
            "Ukhrul"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Manipur.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Meghalaya",
        ministries: {
            chief_minister: "Conrad Sangma",
            home_minister: "Lahkmen Rymbui",
            finance_minister: "M. Ampareen Lyngdoh"
        },
        districts: [
            "East Garo Hills",
            "East Khasi Hills",
            "Jaintia Hills",
            "Ri Bhoi",
            "West Garo Hills",
            "West Khasi Hills"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Meghalaya.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Mizoram",
        ministries: {
            chief_minister: "Zoramthanga",
            home_minister: "L. T. H. Sangliana",
            finance_minister: "L. T. H. Sangliana"
        },
        districts: [
            "Aizawl",
            "Champhai",
            "Kolasib",
            "Lunglei",
            "Mamit",
            "Saiha",
            "Serchhip"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Mizoram.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Nagaland",
        ministries: {
            chief_minister: "Neiphiu Rio",
            home_minister: "Y. Patton",
            finance_minister: "K. M. T. M. Chuba Chang"
        },
        districts: [
            "Dimapur",
            "Kiphire",
            "Mokokchung",
            "Mon",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Nagaland.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Odisha",
        ministries: {
            chief_minister: "Naveen Patnaik",
            home_minister: "Tusharkanti Behera",
            finance_minister: "Niranjan Pujari"
        },
        districts: [
            "Angul",
            "Boudh",
            "Balangir",
            "Balasore",
            "Baragarh",
            "Bhadrak",
            "Bolangir",
            "Cuttack",
            "Deogarh",
            "Dhenkanal",
            "Ganjam",
            "Gajapati",
            "Jagatsinghpur",
            "Jajpur",
            "Jharsuguda",
            "Kalahandi",
            "Kandhamal",
            "Keonjhar",
            "Khurda",
            "Koraput",
            "Mayurbhanj",
            "Nabarangpur",
            "Nayagarh",
            "Nuapada",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Sundargarh"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Odisha.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Punjab",
        ministries: {
            chief_minister: "Bhagwant Mann",
            home_minister: "Bharat Bhushan Ashu",
            finance_minister: "Harpal Singh Cheema"
        },
        districts: [
            "Amritsar",
            "Barnala",
            "Bathinda",
            "Faridkot",
            "Fatehgarh Sahib",
            "Ferozepur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Pathankot",
            "Sangrur",
            "Shaheed Bhagat Singh Nagar",
            "Sri Muktsar Sahib",
            "Tarn Taran"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Punjab.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Rajasthan",
        ministries: {
            chief_minister: "Ashok Gehlot",
            home_minister: "Shanti Kumar Dhariwal",
            finance_minister: "Harish Choudhary"
        },
        districts: [
            "Ajmer",
            "Alwar",
            "Banswara",
            "Baran",
            "Barmar",
            "Bikaner",
            "Chittorgarh",
            "Churu",
            "Dausa",
            "Dholpur",
            "Dungarpur",
            "Ganganagar",
            "Hindaun",
            "Jaipur",
            "Jaisalmer",
            "Jalore",
            "Jhalawar",
            "Jhunjhunu",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Rajsamand",
            "Sawai Madhopur",
            "Sikar",
            "Tonk",
            "Udaipur"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Rajasthan.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Sikkim",
        ministries: {
            chief_minister: "Prem Singh Tamang",
            home_minister: "K. N. Lepcha",
            finance_minister: "A. K. Ghatani"
        },
        districts: [
            "East Sikkim",
            "North Sikkim",
            "South Sikkim",
            "West Sikkim"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Sikkim.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Tamil Nadu",
        ministries: {
            chief_minister: "M. K. Stalin",
            home_minister: "M. S. J. Rajakannappan",
            finance_minister: "Palani N. Palaniappan"
        },
        districts: [
            "Ariyalur",
            "Chengalpattu",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kanchipuram",
            "Kanyakumari",
            "Karur",
            "Madurai",
            "Nagapattinam",
            "Namakkal",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Salem",
            "Sivaganga",
            "Thanjavur",
            "Theni",
            "Thoothukudi",
            "Tiruchirappalli",
            "Tirunelveli",
            "Vellore",
            "Virudhunagar"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Tamil-Nadu.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Telangana",
        ministries: {
            chief_minister: "K. Chandrashekar Rao",
            home_minister: "Mohammed Mahmood Ali",
            finance_minister: "T. Harish Rao"
        },
        districts: [
            "Adilabad",
            "Hyderabad",
            "Jagtial",
            "Jangaon",
            "Jayashankar Bhupalpally",
            "Jogulamba Gadwal",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Mahabubnagar",
            "Mancherial",
            "Medak",
            "Medchal–Malkajgiri",
            "Nalgonda",
            "Nizamabad",
            "Peddapalli",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Wanaparthy",
            "Warangal Rural",
            "Warangal Urban",
            "Yadadri Bhuvanagiri"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Telangana.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Tripura",
        ministries: {
            chief_minister: "Manik Saha",
            home_minister: "Manik Saha",
            finance_minister: "Pranajit Singha Roy"
        },
        districts: [
            "Dhalai",
            "Gomati",
            "Khowai",
            "North Tripura",
            "Sepahijala",
            "South Tripura",
            "Unakoti",
            "West Tripura"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Tripura.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Uttar Pradesh",
        ministries: {
            chief_minister: "Yogi Adityanath",
            home_minister: "Brij Lal",
            finance_minister: "Suresh Khanna"
        },
        districts: [
            "Agra",
            "Aligarh",
            "Ambedkarnagar",
            "Amethi",
            "Auraiya",
            "Ayodhya",
            "Azamgarh",
            "Badaun",
            "Baghpat",
            "Bahraich",
            "Ballia",
            "Banda",
            "Barabanki",
            "Bareilly",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Chandauli",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Etawah",
            "Faizabad",
            "Farrukhabad",
            "Fatehpur",
            "Firozabad",
            "Gautam Buddha Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Hamirpur",
            "Hapur",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Kannauj",
            "Kanpur Dehat",
            "Kanpur Nagar",
            "Kasganj",
            "Kaushambi",
            "Kushinagar",
            "Lakhimpur Kheri",
            "Lalitpur",
            "Lucknow",
            "Maharajganj",
            "Mahoba",
            "Mainpuri",
            "Mathura",
            "Meerut",
            "Mau",
            "Muzaffarnagar",
            "Pilibhit",
            "Pratapgarh",
            "Rae Bareli",
            "Rampur",
            "Saharanpur",
            "Shahjahanpur",
            "Shrawasti",
            "Siddharthnagar",
            "Sitapur",
            "Sonbhadra",
            "Sultanpur",
            "Unnao",
            "Varanasi",
            "Badaun"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Uttar-Pradesh.png"
    },
    {
        id: crypto.randomUUID(),
        name: "Uttarakhand",
        ministries: {
            chief_minister: "Pushkar Singh Dhami",
            home_minister: "Dinesh Mahara",
            finance_minister: "Prem Chand Aggarwal"
        },
        districts: [
            "Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/Uttarakhand.png"
    },
    {
        id: crypto.randomUUID(),
        name: "West Bengal",
        ministries: {
            chief_minister: "Mamata Banerjee",
            home_minister: "Jagdeep Dhankhar",
            finance_minister: "Chandrayee Mukherjee"
        },
        districts: [
            "Alipurduar",
            "Bankura",
            "Birbhum",
            "Bardhaman",
            "Bhowanipore",
            "Cooch Behar",
            "Dakshin Dinajpur",
            "Darjeeling",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Jhargram",
            "Koch Bihar",
            "Kolkata",
            "Malda",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "Purba Medinipur",
            "Paschim Medinipur",
            "Purulia",
            "South 24 Parganas",
            "Uttar Dinajpur"
        ],
        image: "https://www.nlcbharat.org/wp-content/uploads/2023/01/West-Bengal.png"
    }
];

